### ISSUE TITLE
Add missing "author" field to Information Sources

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/extension-geodetic-registry#12]
... then later on switch to Relaton proper.

from discussion with @maccraymer

**Comment by ronaldtse** [comment]
This is also related to #13 .

**Comment by strogonoff** [comment]
The reason author field is missing is that none of the existing item data exported from Java DB has author in information sources. This seems to be an omission with our YAML export. Filed https://github.com/isogr/data-extraction-tools/issues/7
