### ISSUE TITLE
Remove "description" field from Transformation

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/extension-geodetic-registry#19]
from discussion with @maccraymer

**Comment by strogonoff** [comment]
Do we know on which specific classes should we have `description`? (cc @ribose-jeffreylau)

**Comment by ribose-jeffreylau** [comment]
@strogonoff I have one instance of `description` in ISO 19111:2019, for `EX_Extent`.  For 19111:2007, I will need to look at the standard to confirm (I do not possess a copy at this moment).

**Comment by strogonoff** [comment]
We have now remarks instead, applicable for all item classes.
