### ISSUE TITLE
Implement ability to edit "Axes" in all Coordinate System item classes

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/extension-geodetic-registry#23]
Currently there seems to be no way to input such a thing.

<img width="485" alt="Screenshot 2023-03-30 at 5 57 28 PM" src="https://user-images.githubusercontent.com/2649467/228800515-6bafdf63-b5e5-45a5-9433-2f452c344da7.png">

**Comment by strogonoff** [comment]
Axes are editable now. Each axis is a link to Coordinate System Axis register item.
