### ISSUE TITLE
Engineering CRS: add Coordinate System, Base CRS, Operation

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/extension-geodetic-registry#32]
- Coordinate system: link to either Cartesian or Spherical coordinate system
- Operation: link to either Conversion or Transformation
- Base CRS: link to either Geodetic, Engineering, or Vertical

**Comment by strogonoff** [comment]
Engineering CRS now uses the same data type and edit view as all non-compound CRS classes, and therefore has the coordinate system, CRS, and operation fields.
