### ISSUE TITLE
Unit of Measurement: add Standard Unit field, make Measure Type an enum

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/extension-geodetic-registry#42]

**Comment by ribose-jeffreylau** [comment]
Measure type:

<img width="166" alt="Screenshot 2023-06-07 at 17 18 33" src="https://github.com/paneron/extension-geodetic-registry/assets/2649467/c38252c1-acde-4d78-bbff-7e58c569b122">

**Comment by strogonoff** [comment]
Standard unit field is expressed as `baseUnit` in YAML.
