### ISSUE TITLE
Accuracy and parameter values should be strings

### ISSUE THREAD

**Issue by strogonoff** [paneron/extension-geodetic-registry#62]
We should probably not store accuracy values as numbers, since numbers are susceptible to potential inadvertent and unpredictable changes during processing due to floating point issues. It’s a good practice to use a literal representation of the value which will be sure to not change.

This touches on a larger issue, in that we should prefer strings for registered data as they are least ambiguous among the datatypes.

**Comment by strogonoff** [comment]
Check SQL too.

**Comment by strogonoff** [comment]
We are working on data migration procedure to automatically convert any parameter values that are Java objects (decimals, etc.) to raw strings, the same should be done with accuracy values.

**Comment by strogonoff** [comment]
One related effect of not storing values as strings, and this effect Mike has confirmed to be undesirable, is that in the current Java system large parameter values are shown using abbreviated scientific notation, which is apparently not what would be expected.

**Comment by strogonoff** [comment]
It needs to be done, we’ll ask Roger.

**Comment by strogonoff** [comment]
Example of accuracy that is a number:

https://github.com/isogr/registry/blob/f531554f8bbdfc1b1c9a19851ac6c9bcb7b004d3/gr-registry/coordinate-ops--transformation/05b25fbc-c6bf-4d66-86cb-b140e7c27a6a.yaml#L5

**Comment by stefanomunarini** [comment]
Update YAML files (int -> str)

**Comment by stefanomunarini** [comment]
YAML data has been update in https://github.com/isogr/registry/commit/dfca1c0a16508937a97b52a236e74d5ed2a54516

**Comment by stefanomunarini** [comment]
Reopening since the commit above only accounts for *accuracy* and not for parameter values. Shall those be updated as well? @strogonoff just want to confirm the original issue is still relevant in its entirety

**Comment by strogonoff** [comment]
This should have been fixed back in April.
