### ISSUE TITLE
Transformations showing blank tab

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/extension-geodetic-registry#79]
@maccraymer reported that Paneron would show a tab window when double-clicking on the Transformations in the Browse window pane.

However, [staging website](https://geodetic-staging.isotc211.org/#(state:BQIQTg9g7gzgpgLmAIwDYQMYGsDKAXAQz0RUlkTzAFc4AaAB0nohgNQFoALASxjwjABPBJRoBKMbQycCAOwDmcdmDgBHGn3apeedmkxZ289MjbsApACYAHBGQArAHR5uAWzgARXs3gATANQAhOYAzB6hHv5Usr5wAGbcsnABVgBsaf52Ti7uXjA%2ByUEREf6yVKioVgCc-mkZVrYOjnxEcLVhxWG1lpYEGBhw9MS%2BVpa1AOwAwuZTmU0txO3hHV2jfQNDyewQsuwE9PRwbKPVSOrc2DhUyHxgifIAijRCCADkr7TwqHAYwwCSxFcAAUiJwEAB6RgQHxsGDggiWELWcYAVl8qXYcRCcSq7AALABGXxxPbjODIdipAkEqoE5HWKoYPHWcGuAiJRyCAiuVCSbiAvRkeBgJBfH7-QF-DwIDAQAS%2BRKtbb0GDsdiUOQwOICNkuHa0OAAD3oclivgBcFcUpgSAA8nhOHAwLRJnKwArZK1MocwERuDsYBJaPzLewMKgCDBVbL5YriMrVerfbItTq-Tt2PACGBpGdnsJgBg7sQ7gQkCpzioEGxUFJi07uGXgBJJOdLtdbvcnk7hO9PnBvr9khbgaCEGUKnyBVmc5wuBB3Hme0giyHS%2BW1FRuFWa3W142kC3aG3cB3KF3828PmKh%2BbASCHePyrzaGzEso4PIdEJ2AA3bhwFASCxIQ3CoAAKgQyAAKoAEp-DawCvNIciKBWGh4BCUIwqgcIECiGBxAQVQECScQYL4FJ4r0AAMejWASlj4uMIRwHAVSsSEyAhBgrLsrInLcqgHzITIChOpucB8FhTAsLC4KMr4eIooiGI0TRvi%2BPiVTjBSBC%2BASKLsL4KIENYqSWGxKJVDYfEclyPIiSGrjhpGNoxu6cZKNCiYaim2pgLq-qyCJKHiehUmYZCsmsLh8KIsiaIYliOL4kSJIEGSFJUjSdLjAyTIsm%2BAkOcJkjahgVB%2BJByB-L4hoIJYkjuIQSD6JchDEKKVCuGyLyiHQfkwPywU2gNQbYXJHCKcpqnsOpmnabpewGUZJlmRZVk2dYmZHLOS4vIW9brsA6Hbogu6riWB7NkGJ5XDc54KN2Lx9jeEqWg%2BYITi%2Bk2xXsCWouimLYrihLEqS5KUtStL0oyzK7dmubAOoy5HfuTZnTuFR7tdTZHvdZ53M9l5vQO4rDveY4-ZIf1mPhhHEaRmIUVRtH0YxzGsexnHcRgiP7Sjl7o3jG6VhdONXQ2%2BN3Vu7aPcTjyk9e5O3iOX0QkaxCyHg4KWARyDjASNFKDRmVUbpeLsFU6JGdYyDkoyDE0SEBCpIJPISEAA)) shows everything normally.

Individual transformations could be accessed by entering their ID in the search bar of the Home tab.  However, they are not being displayed by Paneron in the Transformations tab.

According to @maccraymer, this problem does not exhibit in the Production registry in Paneron, and that the Transformations tab shows all the transformations.  (**NOTE:** Production registry commit is [3b341224abb9ecb22e820b80f1e3287c0466884e](https://github.com/isogr/registry/commit/3b341224abb9ecb22e820b80f1e3287c0466884e) as of writing.)

Relevant commits:

- [7c516c432d72143c0702730788e7a5df2e947119](https://github.com/isogr/registry-staging/commit/7c516c432d72143c0702730788e7a5df2e947119) (latest commit on Staging as of writing)

**Comment by ribose-jeffreylau** [comment]
A test that I did:

- Paneron 2.2.14
- Same commit (`7c516c`)

I could browse the Transformations tab, but:

- the last item is only up to ID `1038`, unlike in the Staging instance where the last item has ID of `1263`;
- I could only see proposals up to `2024-09-16`, unlike in the Staging instance where there are proposals dated `2024-12-11`, `2024-12-16` and `2024-12-17`.

**Comment by maccraymer** [comment]
I checked again just now and I am still getting an empty Transformations list in Paneron but get a complete list on the staging website. I am using 

- Paneron 2.2.14
- Staging commit 7c516c 

Should I try re-installing the staging repository?

**Comment by ribose-jeffreylau** [comment]
This is interesting.

Now that

- the staging is at commit 4473c1,
- data UI version being 1.0.65,
- Paneron version being v2.2.14,

I can now browse the full list of Transformations in Paneron as well as the website.

@maccraymer Could you see the same thing as I do?  Or is it still a blank tab?

**Comment by maccraymer** [comment]
I can now see all the transformation. Weird I couldn't before making changes to the staging registry and creating a new commit. Anyway, all is good now. You can close this issue.
