### ISSUE TITLE
Make `Coordinate Operation Method` autofill parameter list

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/extension-geodetic-registry#8]
This tracks feature parity with the Java GUI.

## Affected areas

Coordinate Operations

- Concatenated Operation
- Transformation
- Conversion

**Comment by strogonoff** [comment]
@ribose-jeffreylau

> Concatenated Operation

We don’t have any parameters for concatenated operations, do we?

**Comment by ribose-jeffreylau** [comment]
Looking at Example D.9 from 19111:2007, it seems that parameters belong to each individual operations that are being concatenated, and not to the "concatenated operation" itself...

**Comment by strogonoff** [comment]
Excellent. This behavior was already implemented on Transformation and Conversion items…
